---
version: "3.9"
services:
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Aa123456"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
